apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ws
spec:
  selector:
    matchLabels:
      app: hello-ws
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-ws
    spec:
      containers:
        - name: hello-ws
          image: "doc185174/hello-websocket:latest"
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: hello-ws
spec:
  selector:
    app: hello-ws
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080