apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-lua-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: mysite.com
    http:
      paths:
      - path: /api/?(.*)
        backend:
          serviceName: hello
          servicePort: 8080