apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-lua-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  - hosts:
    - lua.example.com
  rules:
  - http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx-lua-gateway
          servicePort: 80
