apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-lua-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-send-timeout: "14400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "14400"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: mysite.com
    http:
      paths:
      - path: /api/?(.*)
        backend:
          serviceName: hello
          servicePort: 80
      - path: /ws/?(.*)
        backend:
          serviceName: hello-ws
          servicePort: 80
      - path: /nginx/?(.*)
        backend:
          serviceName: nginx-lua-gateway
          servicePort: 80