apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-lua-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: lua.example.com
    http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx-lua-gateway
          servicePort: 80
      - path: /ws
        backend:
          serviceName: hello-ws
          servicePort: 80
