apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-lua-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: lua.example.com
    http:
      paths:
      - path: /spring
        backend:
          serviceName: spring
          servicePort: 80
